In [110]:
# import libries
import pandas as pd
import numpy as np
import re

In [111]:
pd.set_option('display.max_colum',None)
pd.set_option('display.max_row',None)
data = pd.read_csv('flats - flats.csv')

In [112]:
data.sample(6)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
892,3 BHK Flat in Sector 111 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Puri Diplomatic Greens4.0 ★,2.65 Crore,"₹ 13,589/sq.ft.",Super Built up area 2215(205.78 sq.m.)Carpet a...,3 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,"7th, Sector 111 Gurgaon, Gurgaon, Haryana",7th of 21 Floors,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Puri diplomatic greens is one of the most popu...,"['5 Fan', '1 Exhaust Fan', '17 Light', '5 AC',...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction5 out of...",R69137466
576,3 BHK Flat in Sector 71 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,CHD Avenue 713.6 ★,1.16 Crore,"₹ 6,655/sq.ft.",Super Built up area 1743(161.93 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"Middle Floor, Sector 71 Gurgaon, Gurgaon, Haryana",5th of 14 Floors,South-West,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",This 3 bhk apartment is available for sale in ...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area5 out of 5', 'Construction3 out of...",C69466170
1265,3 BHK Flat in Sector 49 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Vatika City4.1 ★,1.72 Crore,"₹ 7,818/sq.ft.",Carpet area: 2200 (204.39 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 49 Gurgaon, Gurgaon, Haryana",2nd of 17 Floors,North-East,10+ Year Old,"['BOB ATM', 'PNB ATM', 'HDFC bank ATM', 'YES b...",Vatika city is one of gurgaon's most sought af...,"['1 Bed', '4 Fan', '1 Exhaust Fan', '10 Light'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of...",D69729550
469,3 BHK Flat in Sector 60 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Ireo Skyon4.0 ★,2.65 Crore,"₹ 13,125/sq.ft.",Super Built up area 2045(189.99 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"Block D, Sector 60 Gurgaon, Gurgaon, Haryana",7th of 12 Floors,North-East,5 to 10 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Ireo skyon all sizes available at best price g...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of...",H68412308
1238,3 BHK Flat in Sector 81 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,DLF The Ultima4.0 ★,2.25 Crore,"₹ 10,553/sq.ft.",Super Built up area 2132(198.07 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,Servant Room,"154, Sector 81 Gurgaon, Gurgaon, Haryana",15th of 29 Floors,North-East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",This 3 bhk apartment is available for sale in ...,"['8 Fan', '1 Fridge', '1 Exhaust Fan', '5 Geys...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of...",U68573340
1753,4 BHK Flat in Sector-33 Sohna,https://www.99acres.com/4-bhk-bedroom-apartmen...,Central Park Flower Valley,2.3 Crore,"₹ 12,777/sq.ft.",Carpet area: 1800 (167.23 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Servant Room","Sector-33 Sohna, Gurgaon, Haryana",5th of 13 Floors,North-East,0 to 1 Year Old,"['Golf Course Extension Rd', 'Rajiv Chowk - So...",9 sports academiesMulti-Cuisine restaurantKids...,"['4 Wardrobe', '4 Fan', '18 Light', '1 Chimney...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN,E69609918

In [113]:
data.set_index(data.index+2,inplace=True)

In [114]:
data.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
3,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
4,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
5,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
6,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [115]:
# shape 
data.shape

(3028, 20)

In [116]:
# info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 2 to 3029
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.3+ KB

In [117]:
# Check For duplicates
data.duplicated().sum()

0

In [118]:
# Check For Null Values
data.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [119]:
# Columns to drop -> property_name, link, property_id
data.drop(columns=['link','property_id'], inplace=True)

### By observating data i got these rows unusefull so we remove these rows
[288,2996,2997,2998,2999,3000,3001,3002,3003,3004,3005,2925,2926,2927,2929,2930,2852,2853,2854,2855]

In [120]:
us_rows = [288,2996,2997,2998,2999,3000,3001,3002,3003,3004,3005,2925,2926,2927,2929,2930,2852,2853,2854,2855]
data.loc[us_rows,:]

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
288,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2996,4 BHK Flat in DLF Phase 4,Chanderlok Society,NaN,"₹ 7,234/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,3 BHK Flat in Sector 9A Gurgaon,Jammu and Kashmir Bank Employees CGHS3.7 ★,NaN,"₹ 6,129/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,3 BHK Flat in Sector 37C Gurgaon,ILD Greens4.1 ★,NaN,"₹ 4,723/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,3 BHK Flat in Adarsh Nagar,ss residency,NaN,"₹ 4,818/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3000,3 BHK Flat in Rajendra Park,Uphar lakshya homes,NaN,"₹ 4,200/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3001,2 BHK Flat in Sector 79 Gurgaon,Supertech Araville,NaN,"₹ 9,000/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,3 BHK Flat in Sector 37C Gurgaon,Corona Optus3.9 ★,NaN,"₹ 6,361/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3003,3 BHK Flat in Sector 78 Gurgaon,Umang Monsoon Breeze,NaN,"₹ 6,493/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3004,3 BHK Flat in Sector 88A Gurgaon,Godrej Oasis3.9 ★,NaN,"₹ 8,108/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3005,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon","Godrej Aria , sector 79 , Gurgaon",NaN,"₹ 11,111/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2925,3 BHK Flat in Sector 99A Gurgaon,Pareena Coban Residences,NaN,"₹ 5,759/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2926,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,"₹ 12,437/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,2 BHK Flat in Sector 89 Gurgaon,Greenopolis,NaN,"₹ 4,820/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2929,4 BHK Flat in C Block Sushant Lok Phase 1,Maple Heights,NaN,"₹ 8,888/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2930,2 BHK Flat in Sector 99 Gurgaon,Assotech Blith,NaN,"₹ 6,593/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in Sector 107 Gurgaon,Signature Global Solera3.7 ★,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2853,4 BHK Flat in Sector 53 Gurgaon,Tulip Monsella,NaN,"₹ 33,198/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2854,2 BHK Flat in New Palam Vihar,My Home,NaN,"₹ 4,400/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2855,2 BHK Flat in Sohna,Breez Global Hill View,NaN,"₹ 5,470/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
# drop rows 
data.drop(us_rows,inplace=True)
# now data shape
data.shape

(3008, 18)

In [122]:
# rename columns
data.rename(columns={'area':'price_per_sqft'},inplace=True)
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
5,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
6,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

### Now We Works On Every columns

# 1.Society

In [123]:
data['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Gems                                     32
Smart World Orchard                                  32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         27
Godrej Nature Plus                                   27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
Vatika Gurgaon 213.7 ★                               24
Experion The Heartsong3.9 ★                          24
Eldeco Accolade3.8 ★                                 24
DLF New Town Heights 13.9 ★                          24
Bestech Park View Residency3.9 ★                     23
Tata Primanti4.1 ★                                   22
M3M Heights                                          22
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
Ambience Creacions                                   18
Indiabulls Centrum Park3.7 ★                         18
CHD Avenue 713.6 ★                                   18
Sobha City                                           18
Supertech Araville                                   18
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
M3M Skywalk                                          17
M3M Golfestate4.4 ★                                  17
Godrej Summit3.7 ★                                   17
Bestech Park View Grand Spa4.3 ★                     16
M3M Merlin3.7 ★                                      16
HCBS Sports Ville3.6 ★                               16
Pareena Coban Residences                             16
Umang Monsoon Breeze                                 15
Godrej Oasis3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
DLF The Primus3.9 ★                                  14
Imperia The Esfera                                   14
Orchid Petals4.1 ★                                   14
Ireo Skyon4.0 ★                                      14
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
The Close North4.0 ★                                 14
Ireo Victory Valley4.1 ★                             14
Corona Optus3.9 ★                                    14
Vatika The Seven Lamps3.8 ★                          14
Ireo The Corridors                                   13
Puri Emerald Bay3.7 ★                                13
Bestech Park View Ananda4.2 ★                        13
Central Park Flower Valley                           13
TARC Maceo3.8 ★                                      11
Godrej Aria3.8 ★                                     11
DLF The Skycourt4.2 ★                                11
Alpha Corp GurgaonOne 844.0 ★                        11
SBTL Caladium                                        11
M3M Soulitude                                        11
Raheja Vedaanta3.6 ★                                 11
Adani M2K Oyster Grande3.9 ★                         11
Pyramid Urban Homes 2                                10
Signature Global Synera3.4 ★                         10
Godrej Air                                           10
Emaar MGF Palm Hills4.0 ★                            10
Capital Residences 360                               10
Breez Global Heights4.2 ★                            10
Puri Diplomatic Greens4.0 ★                          10
Breez Global Hill View                               10
Zara Aavaas                                          10
ATS Kocoon                                           10
DLF New Town Heights 24.0 ★                          10
Pivotal Devaan                                       10
Ramprastha The Edge Towers3.5 ★                      10
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
ILD Greens4.1 ★                                       9
Pareena Mi Casa                                       9
Parsvnath Green Ville3.9 ★                            9
GLS Avenue 51                                         8
The Lions CGHS                                        8
Bestech Altura                                        8
Birla Navya                                           8
M3M Skycity                                           8
M3M Capital                                           8
Tulip Ivory3.5 ★                                      8
AVL 36 Gurgaon3.7 ★                                   8
Vatika Lifestyle Homes3.8 ★                           8
Emaar Digihomes                                       8
ss                                                    8
Orris Aster Court Premier                             8
Sare Green ParC Phase 3                               7
AIPL Zen Residences                                   7
Assotech Blith                                        7
Orris Carnation Residency3.7 ★                        7
Ireo The Grand Arch4.0 ★                              7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Signature Andour Heights3.8 ★                         7
Ansal Housing Highland Park                           7
Trisara Our Homes 3                                   7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
Signature Global City                                 7
Emaar Imperial Gardens3.8 ★                           7
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
HSIIDC Sidco Aravali                                  6
Signature Global City 63A                             6
Supertech Hues                                        6
Shapoorji Pallonji Joyville Gurugram                  6
Mapsko Royale Ville3.7 ★                              6
Kiran Residency                                       6
Sidhartha NCR One Phase 14.2 ★                        6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Bestech Park View City4.1 ★                           6
Suncity Vatsal Valley                                 6
Signature Global Park 4                               6
Hero Homes                                            6
BPTP Astaire Gardens3.7 ★                             6
Signature The Roselia3.6 ★                            6
M3M Sierra 68                                         6
Pioneer Araya3.8 ★                                    6
Pyramid Urban                                         6
Apna Enclave                                          5
Signature Global the Millennia                        5
Essel Towers                                          5
Satya The Hermitage3.5 ★                              5
DLF Park Place4.1 ★                                   5
Pareena Laxmi Apartments3.6 ★                         5
Green Court3.7 ★                                      5
Krisumi Waterfall Residences                          5
ATS Marigold                                          5
Ireo Uptown4.1 ★                                      5
Signature Global City 81                              5
Emaar MGF Emerald Estate3.8 ★                         5
M3M The Marina4.0 ★                                   5
Silverglades The Melia                                5
Ashiana Anmol3.5 ★                                    5
DLF Regency Park 24.0 ★                               5
Conscient Elevate                                     5
Central Park Flower Valley Aqua Front Towers          5
Godrej Habitat                                        5
Signature Global Grand IVA3.9 ★                       5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
Vatika Sovereign Park                                 5
Central Park Resorts4.4 ★                             5
Vatika City Homes3.9 ★                                5
Pioneer Park3.8 ★                                     5
Greenopolis                                           5
Signature Global City 92                              5
Unitech Vistas                                        4
Prime Habitat                                         4
Sare Petioles                                         4
Unitech Fresco3.8 ★                                   4
Tata Gurgaon Gateway3.8 ★                             4
Global Hill View                                      4
ILD Grand                                             4
Corona Gracieux                                       4
Raheja Navodaya3.6 ★                                  4
Railway Officers RPF Society                          4
Godrej Frontier3.7 ★                                  4
Orris Aster Court                                     4
Krrish Provence Estate                                4
Godrej Icon                                           4
Lotus Homz4.0 ★                                       4
DLF New Town Heights3.7 ★                             4
Emaar Palm Heights                                    4
DLF The Skycourt                                      4
Signature The Serenas                                 4
Ramprastha Primera                                    4
Ramprastha Skyz                                       4
SS The Coralwood3.4 ★                                 4
Tulip Monsella                                        4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Ambience Lagoon3.9 ★                                  3
Pivotal Riddhi Siddhi                                 3
Shri Ram Apartments                                   3
DLF The Arbour                                        3
Tulip Petals3.6 ★                                     3
DLF Express Greens3.9 ★                               3
Dhoot Time Residency4.0 ★                             3
Sare Green Parc 2                                     3
Unitech Uniworld Gardens3.8 ★                         3
Unitech Sunbreeze                                     3
Siddhartha Apartment                                  3
Raheja Atharva3.6 ★                                   3
DLF Royalton Tower                                    3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Shri Banke Bihari Society3.8 ★                        3
Conscient Habitat3.6 ★                                3
Satya Element One                                     3
Mahindra Aura4.2 ★                                    3
Shree Arihant Apartment                               3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Apex Our Homes                                        3
Paras Quartier                                        3
Puri Diplomatic Greens3.9 ★                           3
Vatika Independent Floors3.8 ★                        3
Guru Gram Haryana CGHS4.1 ★                           3
The Roselia 2                                         3
Tulip Purple                                          3
ATS Kocoon4.2 ★                                       3
Kendriya Vihar4.1 ★                                   3
Valley View Estate                                    3
Whiteland Blissville                                  3
Sidhartha NCR Greens4.3 ★                             3
Signature Global Solera 2                             3
Sunischit Apartments                                  3
Spaze Privvy The Address3.9 ★                         3
Maxworth City Residences                              3
AFNHB Jalvayu Vihar3.7 ★                              3
Sukhshanti Apartment                                  3
Sare Green Parc                                       3
DLF The Grove                                         3
Sapphire Eighty Three                                 3
Pyramid Elite                                         3
Tulip White3.5 ★                                      3
Bestech Park View City 23.9 ★                         3
Brisk Lumbini Terrace Homes                           3
Chintels Paradiso3.9 ★                                3
Raheja Sampada                                        3
Sidhartha NCR One                                     3
Unitech The Residences3.7 ★                           3
Deepak Minda                                          3
Smriti Apartment                                      3
SS Almeria                                            3
Adani Aangan Arcade                                   3
Krrish Florence Estate                                3
Piedmont Taksila heights3.6 ★                         3
Vatika Xpressions                                     3
AIPL Club Residences                                  3
DLF Belvedere Towers3.8 ★                             3
Raheja Revanta                                        3
Essel Tower                                           3
DLF Carlton Estate4.0 ★                               3
Unitech Heritage City                                 3
Vipul Belmonte3.9 ★                                   2
Emaar MGF The Enclave                                 2
BPTP Mansions Park Prime                              2
Supertech Hilltown                                    2
Samaspurkunj                                          2
BPTP Amstoria3.8 ★                                    2
Suncity Avenue 1023.9 ★                               2
BPTP Freedom Park Life4.0 ★                           2
Mittal Surya Vihar                                    2
DLF The Belaire3.9 ★                                  2
Suposhaa Smartworld Orchard                           2
Residency Grand                                       2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Paras Irene3.7 ★                                      2
Ardee City3.8 ★                                       2
Ramprastha City                                       2
M3M Ikonic                                            2
Puri The Aravallis                                    2
My Home                                               2
Bestech Park View Sanskruti4.1 ★                      2
Shapoorji Pallonji Joyville                           2
The Penthouses at the Hibiscus                        2
Ashiana Anmol                                         2
Oriental Valley CHS                                   2
Tulsiani Easy in Homes                                2
NBCC Heights3.9 ★                                     2
Aqua Front Towers                                     2
Supertech Hill Town                                   2
Sahara Grace                                          2
Housing Board Colony                                  2
Suncity Avenue 76                                     2
HCBS Sports Ville                                     2
Godrej Nature Plus Serenity                           2
Adani Aangan Galleria                                 2
Tulip Orange3.9 ★                                     2
Central Park 2 Bellevue                               2
Raheja Atlantis3.8 ★                                  2
SS Hibiscus                                           2
Ansal API Esencia3.7 ★                                2
AWHO Shanti Vihar4.0 ★                                2
Ganga Apartment                                       2
ROF Aalayas3.8 ★                                      2
M3M Sky Lofts                                         2
Signature Global The Millennia 3                      2
Orchid Island4.2 ★                                    2
Emaar MGF Palm Studios                                2
DLF The Icon3.7 ★                                     2
Vatika Emilia Floors3.7 ★                             2
Tulip Violet                                          2
Tulip Leaf                                            2
Viridian The Plaza 106                                2
Professors Enclave CGHS                               2
Breeze Global Heights                                 2
Today Callidora                                       2
Mahindra Luminare4.0 ★                                2
Vasant Appartments                                    2
M3M Urbana                                            2
Green Campus CHS                                      2
Elan The Presidential                                 2
Maruti Vihar                                          2
Milan CGHS 9                                          2
Ansal Heights3.2 ★                                    2
Surendra Avenue 69                                    2
Suncity Heights3.7 ★                                  2
Pioneer Urban Presidia                                2
Vipul World Floors                                    2
Lavanya Apartments                                    2
Ramprastha The Atrium3.4 ★                            2
Bestech Spa Signature                                 2
M3M Latitude                                          2
Ambience Caitriona                                    2
Unitech Uniworld Gardens 23.4 ★                       2
BPTP Pedestal                                         2
MRG World Ultimus                                     2
Bhagwati Sadan                                        2
Ansal API Celebrity Suites                            2
CGHS Airport Apartment                                2
Park Royal Apartment                                  2
Apartment                                             2
Sidhivinayak Apartments                               2
Landmark The Residency                                2
Mapsko Paradise3.9 ★                                  2
The Close South3.9 ★                                  2
Element One Service                                   2
DLF The Crest3.6 ★                                    2
Dlf City                                              2
om appartments                                        2
Silverglades Hightown Residences                      2
Palam Vihar Society                                   2
lagoon apartment                                      2
Vatika INXT Floors                                    2
Raheja Vanya                                          2
BSF CHS                                               1
Lord Krishna                                          1
CGHS Hewo Apartments3.7 ★                             1
Bestech Park View Ananda                              1
Krishna Apartment                                     1

In [124]:
data['society'].nunique()

636

In [125]:
# Check For Null Values
data[data['society'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2769,2 BHK Flat in Sector 78 Gurgaon,NaN,60 Lac,"₹ 3,692/sq.ft.",Built Up area: 1625 (150.97 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [126]:
# Fill Null value
data['society'] = data['society'].fillna('Not Specify')

In [127]:
# Remove ratings from string
data['society'] = data['society'].apply(lambda x:re.sub(r'\d+(\.\d+)?\s*★', '', x).strip() )

In [128]:
# convert society names into lower case
data['society'] = data['society'].apply(lambda x : x.lower())

In [129]:
data['society'].value_counts().shape

(602,)

In [130]:
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
5,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
6,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# 2.Price

In [131]:
data['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
2.35 Crore          23
1.85 Crore          23
3 Crore             22
70 Lac              21
55 Lac              20
2.25 Crore          20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
2.6 Crore           15
1.38 Crore          15
2.45 Crore          14
3.4 Crore           14
2.15 Crore          14
1.32 Crore          13
3.25 Crore          13
78 Lac              13
92 Lac              13
82 Lac              13
38 Lac              13
2.7 Crore           13
1.95 Crore          12
1.42 Crore          12
5 Crore             12
42 Lac              12
2.8 Crore           12
88 Lac              11
32 Lac              11
25 Lac              11
1.08 Crore          11
Price on Request    11
28 Lac              10
1.28 Crore          10
87 Lac              10
26 Lac              10
1.78 Crore          10
1.12 Crore          10
2.55 Crore          10
1.68 Crore           9
3.45 Crore           9
36 Lac               9
22 Lac               9
2.05 Crore           9
4 Crore              9
1.72 Crore           9
99 Lac               9
2.85 Crore           9
27 Lac               8
1.76 Crore           8
98 Lac               8
1.18 Crore           8
1.26 Crore           8
1.54 Crore           8
4.25 Crore           8
2.75 Crore           8
3.2 Crore            8
6 Crore              8
48 Lac               8
6.5 Crore            8
20 Lac               8
56 Lac               8
86 Lac               8
1.36 Crore           7
1.27 Crore           7
97 Lac               7
3.7 Crore            7
1.19 Crore           7
3.3 Crore            7
72 Lac               7
2.9 Crore            7
1.29 Crore           7
46 Lac               7
39 Lac               7
1.02 Crore           7
1.99 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.49 Crore           6
1.01 Crore           6
2.95 Crore           6
3.9 Crore            6
96 Lac               6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.98 Crore           6
21 Lac               6
54 Lac               6
1.39 Crore           6
3.35 Crore           6
1.13 Crore           6
71.5 Lac             6
37 Lac               6
4.1 Crore            6
1.34 Crore           6
3.05 Crore           6
1.14 Crore           6
1.16 Crore           6
1.51 Crore           6
1.24 Crore           5
1.33 Crore           5
1.17 Crore           5
2.22 Crore           5
6.75 Crore           5
1.91 Crore           5
1.82 Crore           5
2.78 Crore           5
1.69 Crore           5
1.44 Crore           5
49 Lac               5
3.75 Crore           5
1.92 Crore           5
1.43 Crore           5
66 Lac               5
2.29 Crore           5
1.79 Crore           5
93 Lac               5
1.62 Crore           5
1.83 Crore           5
1.93 Crore           5
4.5 Crore            5
64 Lac               5
2.12 Crore           5
29 Lac               5
24 Lac               5
1.47 Crore           5
68 Lac               5
1.64 Crore           4
2.09 Crore           4
1.37 Crore           4
5.25 Crore           4
3.6 Crore            4
4.3 Crore            4
5.6 Crore            4
1.22 Crore           4
58 Lac               4
4.85 Crore           4
62 Lac               4
1.23 Crore           4
1.77 Crore           4
41.5 Lac             4
1.52 Crore           4
28.5 Lac             4
1.73 Crore           4
33 Lac               4
7 Crore              4
1.31 Crore           4
36.5 Lac             4
1.48 Crore           4
5.9 Crore            4
3.95 Crore           4
6.15 Crore           4
73 Lac               4
1.58 Crore           4
1.71 Crore           4
89 Lac               4
67 Lac               4
31 Lac               4
1.66 Crore           4
74 Lac               4
3.1 Crore            4
2.24 Crore           3
83 Lac               3
72.5 Lac             3
47 Lac               3
2.36 Crore           3
1.21 Crore           3
1.04 Crore           3
4.75 Crore           3
2.03 Crore           3
3.8 Crore            3
64.5 Lac             3
91 Lac               3
5.8 Crore            3
4.8 Crore            3
1.67 Crore           3
2.51 Crore           3
3.49 Crore           3
2.01 Crore           3
2.08 Crore           3
51 Lac               3
52 Lac               3
84 Lac               3
69 Lac               3
1.57 Crore           3
1.41 Crore           3
3.15 Crore           3
2.79 Crore           3
3.85 Crore           3
2.28 Crore           3
34 Lac               3
1.63 Crore           3
94 Lac               3
1.09 Crore           3
4.2 Crore            3
1.88 Crore           3
2.33 Crore           3
2.23 Crore           2
1.46 Crore           2
77.5 Lac             2
53.5 Lac             2
4.49 Crore           2
2.58 Crore           2
6.2 Crore            2
8.5 Crore            2
2.14 Crore           2
27.1 Lac             2
53 Lac               2
2.52 Crore           2
8 Crore              2
2.41 Crore           2
2.57 Crore           2
56.2 Lac             2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
4.26 Crore           2
2.13 Crore           2
2.02 Crore           2
5.2 Crore            2
14 Crore             2
2.87 Crore           2
2.99 Crore           2
2.26 Crore           2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.17 Crore           2
25.5 Lac             2
4.55 Crore           2
7.5 Crore            2
27.75 Lac            2
4.45 Crore           2
4.7 Crore            2
2.04 Crore           2
11 Crore             2
88.5 Lac             2
54.8 Lac             1
63.4 Lac             1
82.5 Lac             1
3.78 Crore           1
2.06 Crore           1
2.07 Crore           1
3.98 Crore           1
7.4 Crore            1
4.02 Crore           1
2.64 Crore           1
44 Lac               1
37.1 Lac             1
97.5 Lac             1
2.38 Crore           1
2.49 Crore           1
97.04 Lac            1
98.88 Lac            1
2.32 Crore           1
4.21 Crore           1
4.16 Crore           1
15 Crore             1
4.52 Crore           1
89.77 Lac            1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
1.84 Crore           1
8.44 Crore           1
68.85 Lac            1
39.5 Lac             1
13.2 Crore           1
2.92 Crore           1
61 Lac               1
64.45 Lac            1
2.69 Crore           1
3.99 Crore           1
2.96 Crore           1
57 Lac               1
95.5 Lac             1
37.5 Lac             1
96.07 Lac            1
94.5 Lac             1
29.8 Lac             1
19 Lac               1
88.4 Lac             1
6.02 Crore           1
32.5 Lac             1
7.9 Crore            1
70.85 Lac            1
3.23 Crore           1
40.3 Lac             1
3.72 Crore           1
94.99 Lac            1
1.86 Crore           1
2.54 Crore           1
9 Crore              1
7.52 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
86.92 Lac            1
49.5 Lac             1
16 Lac               1
2.44 Crore           1
2.86 Crore           1
1.97 Crore           1
1.53 Crore           1
7.8 Crore            1
4.4 Crore            1
1.74 Crore           1
2.72 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.21 Crore           1
2.63 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
4.95 Crore           1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
98.1 Lac             1
55.5 Lac             1
9.3 Crore            1
2.77 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
42.5 Lac             1
1.11 Crore           1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
1.06 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
62.5 Lac             1
Name: count, dtype: int64

In [132]:
data['price'].value_counts().shape

(439,)

In [133]:
data[data['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
27,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1647,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1975,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2057,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2360,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2525,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2552,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2643,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2962,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2975,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2976,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [134]:
# We drop rows where price = Price on Request	 because these rows doesnt help us to predict price
ind = data[data['price'] == 'Price on Request'].index
data.drop(ind,inplace=True)

In [135]:
data[data['price'] == 'Price on Request']

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [136]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [137]:
data['price'] = data['price'].str.split(' ').apply(treat_price)

In [138]:
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
5,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
6,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# 3.Price_per_square_fit

In [139]:
data['price_per_sqft'] = data['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

# 4.bedRoom

In [140]:
data['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [141]:
data[data['bedRoom'].isnull()]

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [142]:
data['bedRoom'] = data['bedRoom'].str.split(' ').str.get(0).astype('int')

In [143]:
data[data['bathroom'].isnull()]

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [144]:
data['bathroom'] = data['bathroom'].str.split(' ').str.get(0).astype('int')

In [145]:
data['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [146]:
data['balcony'] = data['balcony'].str.split(' ').str.get(0).str.replace("+","").str.replace("No","0").astype('int')

In [147]:
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
5,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
6,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# 5.additionalRoom

In [148]:
data['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [149]:
data['additionalRoom'].isnull().sum()

1305

In [150]:
data['additionalRoom'].fillna('Not available',inplace=True)

In [151]:
data['additionalRoom'] = data['additionalRoom'].str.lower()

In [152]:
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
5,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
6,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# 6.floorNum

In [153]:
data['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
3rd   of 14 Floors          24
5th   of 14 Floors          24
8th   of 19 Floors          24
11st   of 14 Floors         23
1st   of 1 Floors           23
9th   of 14 Floors          23
9th   of 9 Floors           23
5th   of 12 Floors          22
2nd   of 3 Floors           22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
10th   of 18 Floors         17
9th   of 13 Floors          17
7th   of 15 Floors          17
12nd   of 12 Floors         17
Ground of 1 Floors          17
7th   of 18 Floors          17
3rd   of 18 Floors          16
5th   of 15 Floors          16
9th   of 15 Floors          15
1st   of 3 Floors           15
2nd   of 12 Floors          15
6th   of 12 Floors          15
6th   of 19 Floors          14
Ground of 4 Floors          13
3rd   of 13 Floors          13
5th   of 5 Floors           13
1st   of 2 Floors           13
7th   of 7 Floors           13
10th   of 26 Floors         13
6th   of 10 Floors          13
6th   of 15 Floors          12
10th   of 10 Floors         12
17th   of 17 Floors         11
4th   of 10 Floors          11
11st   of 18 Floors         11
9th   of 26 Floors          11
15th   of 19 Floors         11
9th   of 24 Floors          11
6th   of 6 Floors           11
16th   of 19 Floors         11
8th   of 8 Floors           11
8th   of 12 Floors          11
4th   of 13 Floors          11
7th   of 26 Floors          10
4th   of 12 Floors          10
7th   of 13 Floors          10
2nd   of 19 Floors          10
7th   of 21 Floors          10
12nd   of 18 Floors         10
6th   of 13 Floors          10
4th   of 15 Floors          10
1st   of 26 Floors          10
3rd   of 9 Floors           10
10th   of 12 Floors         10
3rd   of 5 Floors           10
14th   of 15 Floors          9
14th   of 19 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
3rd   of 12 Floors           9
18th   of 19 Floors          9
8th   of 15 Floors           9
6th   of 16 Floors           9
15th   of 29 Floors          9
8th   of 22 Floors           9
9th   of 20 Floors           9
7th   of 17 Floors           9
13rd   of 14 Floors          9
7th   of 12 Floors           9
6th   of 26 Floors           9
12nd   of 19 Floors          8
10th   of 17 Floors          8
5th   of 9 Floors            8
3rd   of 15 Floors           8
2nd   of 8 Floors            8
9th   of 18 Floors           8
8th   of 24 Floors           8
10th   of 13 Floors          8
8th   of 26 Floors           8
1st   of 19 Floors           8
2nd   of 15 Floors           8
4th   of 26 Floors           8
12nd   of 26 Floors          8
3rd   of 19 Floors           8
8th   of 13 Floors           8
12nd   of 24 Floors          8
9th   of 12 Floors           8
5th   of 13 Floors           8
2nd   of 5 Floors            8
14th   of 24 Floors          8
4th   of 19 Floors           7
9th   of 19 Floors           7
16th   of 16 Floors          7
5th   of 29 Floors           7
11st   of 24 Floors          7
11st   of 11 Floors          7
2nd   of 13 Floors           7
7th   of 19 Floors           7
2nd   of 17 Floors           7
12nd   of 13 Floors          7
11st   of 26 Floors          7
1st   of 13 Floors           7
11st   of 13 Floors          7
8th   of 21 Floors           7
10th   of 21 Floors          7
8th   of 10 Floors           7
13rd   of 13 Floors          7
2nd   of 10 Floors           7
5th   of 20 Floors           7
12nd   of 15 Floors          7
11st   of 12 Floors          6
Ground of 16 Floors          6
5th   of 22 Floors           6
1st   of 5 Floors            6
1st   of 10 Floors           6
2nd   of 20 Floors           6
14th   of 27 Floors          6
16th   of 18 Floors          6
12nd   of 22 Floors          6
11st   of 19 Floors          6
17th   of 19 Floors          6
10th   of 29 Floors          6
10th   of 20 Floors          6
6th   of 9 Floors            6
19th   of 19 Floors          6
Ground of 3 Floors           6
3rd   of 25 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
4th   of 18 Floors           6
15th   of 15 Floors          6
5th   of 25 Floors           6
5th   of 10 Floors           6
10th   of 15 Floors          6
7th   of 20 Floors           6
8th   of 30 Floors           5
11st   of 16 Floors          5
7th   of 8 Floors            5
4th   of 9 Floors            5
9th   of 11 Floors           5
7th   of 27 Floors           5
9th   of 30 Floors           5
8th   of 9 Floors            5
9th   of 22 Floors           5
15th   of 28 Floors          5
4th   of 27 Floors           5
6th   of 17 Floors           5
3rd   of 20 Floors           5
15th   of 18 Floors          5
18th   of 29 Floors          5
10th   of 25 Floors          5
12nd   of 29 Floors          5
5th   of 8 Floors            5
Ground of 19 Floors          5
4th   of 22 Floors           5
6th   of 20 Floors           5
15th   of 21 Floors          5
Ground of 12 Floors          5
11st   of 25 Floors          5
1st   of 12 Floors           5
10th   of 24 Floors          5
10th   of 27 Floors          5
Ground of 21 Floors          5
6th   of 11 Floors           5
16th   of 26 Floors          5
11st   of 30 Floors          5
1st   of 7 Floors            5
1st   of 15 Floors           5
14th   of 16 Floors          5
5th   of 19 Floors           5
14th   of 29 Floors          5
11st   of 29 Floors          5
12nd   of 21 Floors          5
25th   of 25 Floors          4
17th   of 25 Floors          4
13rd   of 21 Floors          4
13rd   of 19 Floors          4
20th   of 26 Floors          4
7th   of 11 Floors           4
8th   of 16 Floors           4
3rd   of 17 Floors           4
12nd   of 30 Floors          4
5th   of 16 Floors           4
7th   of 24 Floors           4
13rd   of 25 Floors          4
17th   of 26 Floors          4
15th   of 16 Floors          4
8th   of 20 Floors           4
3rd   of 10 Floors           4
2nd   of 11 Floors           4
15th   of 26 Floors          4
3rd   of 22 Floors           4
5th   of 24 Floors           4
5th   of 23 Floors           4
Ground of 13 Floors          4
6th   of 30 Floors           4
17th   of 18 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
2nd   of 9 Floors            4
22nd   of 30 Floors          4
15th   of 23 Floors          4
Ground of 17 Floors          4
17th   of 24 Floors          4
15th   of 32 Floors          4
7th   of 9 Floors            4
3rd   of 11 Floors           4
20th   of 20 Floors          4
23rd   of 26 Floors          4
18th   of 32 Floors          4
14th   of 21 Floors          4
2nd   of 16 Floors           4
7th   of 10 Floors           4
19th   of 40 Floors          4
9th   of 10 Floors           4
12nd   of 16 Floors          4
14th   of 17 Floors          4
4th   of 8 Floors            4
11st   of 17 Floors          4
11st   of 15 Floors          4
14th   of 18 Floors          4
19th   of 24 Floors          4
1st   of 18 Floors           4
11st   of 20 Floors          4
22nd   of 24 Floors          4
3rd   of 26 Floors           3
3rd   of 16 Floors           3
10th   of 16 Floors          3
13rd   of 15 Floors          3
10th   of 28 Floors          3
12nd   of 23 Floors          3
4th   of 20 Floors           3
2nd   of 26 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
8th   of 17 Floors           3
21st   of 24 Floors          3
19th   of 21 Floors          3
17th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 21 Floors           3
27th   of 27 Floors          3
14th   of 32 Floors          3
11st   of 27 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
24th   of 24 Floors          3
21st   of 22 Floors          3
17th   of 20 Floors          3
4th   of 16 Floors           3
6th   of 29 Floors           3
6th   of 24 Floors           3
8th   of 25 Floors           3
30th   of 32 Floors          3
19th   of 30 Floors          3
4th   of 29 Floors           3
17th   of 29 Floors          3
18th   of 18 Floors          3
6th   of 21 Floors           3
5th   of 17 Floors           3
1st   of 25 Floors           3
5th   of 26 Floors           3
19th   of 29 Floors          3
18th   of 30 Floors          3
23rd   of 23 Floors          3
12nd   of 27 Floors          3
18th   of 26 Floors          3
8th   of 11 Floors           3
6th   of 22 Floors           3
6th   of 23 Floors           3
7th   of 23 Floors           3
15th   of 20 Floors          3
15th   of 40 Floors          3
15th   of 22 Floors          3
Ground of 18 Floors          3
16th   of 20 Floors          3
9th   of 21 Floors           3
3rd   of 8 Floors            3
6th   of 8 Floors            3
15th   of 39 Floors          3
20th   of 28 Floors          3
8th   of 40 Floors           3
Ground of 26 Floors          3
10th   of 30 Floors          3
26th   of 30 Floors          3
5th   of 30 Floors           3
9th   of 16 Floors           3
9th   of 40 Floors           3
11st   of 23 Floors          2
Lower Ground of 4 Floors     2
2nd   of 40 Floors           2
23rd   of 29 Floors          2
21st   of 27 Floors          2
13rd   of 20 Floors          2
9th   of 29 Floors           2
10th   of 40 Floors          2
25th   of 29 Floors          2
7th   of 22 Floors           2
13rd   of 30 Floors          2
4th   of 34 Floors           2
8th   of 23 Floors           2
9th   of 27 Floors           2
19th   of 27 Floors          2
3rd   of 24 Floors           2
27th   of 29 Floors          2
2nd   of 28 Floors           2
40th   of 40 Floors          2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
2nd   of 18 Floors           2
2nd   of 7 Floors            2
2nd   of 25 Floors           2
24th   of 30 Floors          2
2nd   of 6 Floors            2
20th   of 22 Floors          2
22nd   of 25 Floors          2
2nd   of 32 Floors           2
43   of 47 Floors            2
1st   of 30 Floors           2
1st   of 20 Floors           2
15th   of 31 Floors          2
1st   of 8 Floors            2
11st   of 21 Floors          2
23rd   of 34 Floors          2
16th   of 34 Floors          2
18th   of 24 Floors          2
16th   of 30 Floors          2
16th   of 27 Floors          2
7th   of 30 Floors           2
14th   of 20 Floors          2
19th   of 20 Floors          2
16th   of 21 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 24 Floors          2
20th   of 23 Floors          2
16th   of 36 Floors          2
9th   of 28 Floors           2
2nd   of 24 Floors           2
1st   of 17 Floors           2
3rd   of 33 Floors           2
8th   of 32 Floors           2
10th   of 32 Floors          2
Ground of 51 Floors          2
39th   of 40 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
13rd   of 40 Floors          2
20th   of 25 Floors          2
9th   of 17 Floors           2
4th   of 5 Floors            2
12nd   of 25 Floors          2
1st   of 24 Floors           2
6th   of 31 Floors           2
7th   of 29 Floors           2
1st   of 22 Floors           2
10th   of 22 Floors          2
5th   of 11 Floors           2
2nd   of 21 Floors           2
17th   of 33 Floors          2
8th   of 28 Floors           2
10th   of 11 Floors          2
Ground of 23 Floors          2
8th   of 29 Floors           2
3rd   of 27 Floors           2
14th   of 28 Floors          2
3rd   of 32 Floors           2
15th   of 17 Floors          2
16th   of 32 Floors          2
3rd   of 29 Floors           2
18th   of 21 Floors          2
15th   of 45 Floors          2
7th   of 36 Floors           2
1st   of 16 Floors           2
4th   of 11 Floors           2
5th   of 35 Floors           1
13rd   of 34 Floors          1
3rd   of 28 Floors           1
12nd   of 40 Floors          1
7th   of 40 Floors           1
13rd   of 26 Floors          1
17th   of 28 Floors          1
18th   of 35 Floors          1
22nd   of 40 Floors          1
14th   of 25 Floors          1
Ground of 2 Floors           1
16th   of 41 Floors          1
13rd   of 22 Floors          1
3rd   of 7 Floors            1
17th   of 31 Floors          1
Ground of 40 Floors          1
Ground of 5 Floors           1
21st   of 23 Floors          1
Ground of 22 Floors          1
10th   of 33 Floors          1
3rd   of 30 Floors           1
3rd   of 31 Floors           1
Lower Ground of 1 Floors     1
19th   of 32 Floors          1
Ground of 6 Floors           1
13rd   of 17 Floors          1
20th   of 24 Floors          1
45   of 47 Floors            1
22nd   of 23 Floors          1
30th   of 34 Floors          1
Ground of 25 Floors          1
16th   of 45 Floors          1
1st   of 6 Floors            1
9th   of 25 Floors           1
13rd   of 47 Floors          1
5th   of 36 Floors           1
34th   of 34 Floors          1
34th   of 42 Floors          1
9th   of 23 Floors           1
29th   of 39 Floors          1
33rd   of 33 Floors          1
27th   of 30 Floors          1
4th   of 6 Floors            1
7th   of 28 Floors           1
8th   of 35 Floors           1
Ground of 29 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
5th   of 6 Floors            1
22nd   of 26 Floors          1
3rd   of 36 Floors           1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
14th   of 41 Floors          1
5th   of 34 Floors           1
24th   of 36 Floors          1
17th   of 22 Floors          1
21st   of 36 Floors          1
23rd   of 24 Floors          1
18th   of 22 Floors          1
Basement of 13 Floors        1
12nd   of 34 Floors          1
17th   of 47 Floors          1
18th   of 20 Floors          1
24th   of 27 Floors          1
21st   of 26 Floors          1
26th   of 47 Floors          1
7th   of 25 Floors           1
Ground of 11 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
1st   of 44 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
11st   of 22 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
25th   of 36 Floors          1
21st   of 28 Floors          1
7th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
Ground of 24 Floors          1
35th   of 35 Floors          1
10th   of 39 Floors          1
33rd   of 48 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
20th   of 34 Floors          1
29th   of 31 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
31st   of 40 Floors          1
9th   of 42 Floors           1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
16th   of 25 Floors          1
6th   of 25 Floors           1
3rd   of 40 Floors           1
12nd   of 39 Floors          1
8th   of 31 Floors           1
20th   of 30 Floors          1
18th   of 51 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
38th   of 40 Floors          1
15th   of 27 Floors          1
18th   of 40 Floors          1
35th   of 51 Floors          1
22nd   of 28 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [154]:
data['floorNum'].isnull().sum()

2

In [160]:
data[data['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
183,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2769,2 BHK Flat in Sector 78 Gurgaon,not specify,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [155]:
data['floorNum'] = data['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [156]:
data.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
5,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
6,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [157]:
data['floorNum'].value_counts()

floorNum
2     258
3     248
1     223
4     203
8     200
7     188
10    185
6     185
5     172
9     171
12    160
0     133
14    117
11    115
15     83
16     53
17     51
13     43
18     38
19     34
20     25
21     15
23     15
22     14
24     11
25      9
27      7
26      5
30      5
28      4
31      4
33      3
29      3
43      2
35      2
32      2
39      2
34      2
40      2
38      1
45      1
44      1
Name: count, dtype: int64

# 7. facing

In [158]:
data['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [162]:
data['facing'].isnull().sum()

0

In [161]:
data['facing'].fillna('NA',inplace=True)

In [164]:
data['facing'].value_counts()

facing
NA            874
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [165]:
data.insert(loc=4,column='area',value=round((data['price']*10000000)/data['price_per_sqft']))

In [168]:
data.insert(loc=1,column='property_type',value='flat')

In [169]:
data.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
5,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
6,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [171]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 2 to 3029
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   property_type    2997 non-null   object
 2   society          2997 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2997 non-null   object
 7   bedRoom          2997 non-null   int32
 8   bathroom         2997 non-null   int32
 9   balcony          2997 non-null   int32
 10  additionalRoom   2997 non-null   object
 11  address          2991 non-null   object
 12  floorNum         2995 non-null   object
 13  facing           2997 non-null   object
 14  agePossession    2996 non-null   object
 15  nearbyLocations  2906 non-null   object
 16  description      2997 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2590 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int32(3), object(14)
memory usage: 456.6+ KB

In [173]:
data.shape

(2997, 20)

In [174]:
data.to_csv('flats_cleaned.csv',index=False)